spring:
  application:
      name: Gradle
  datasource:
      url: jdbc:mysql://localhost:3300/test
      username: root
      password: Vu123456

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
      show-sql: true
server:
  port: 1001
appConfig:
  default-page-size: 10
  default-page-number: 0