spring :
  datasource:
    url: jdbc:postgresql://localhost:5430/flyway?autoreconnect=true
    username: postgres
    password: Vu123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db.migration

server:
  port: 1001

appConfig:
  default-page-size: 10
  default-page-number: 0
#info :
#  app:
#    name: Spring Sample Application
#    description: This is my first spring boot application
#    version: 1.0.0